Repository TUK-SPORTIFY/sportify-frontend, pull requests merged in 2024-12, with the labels that each got.

#23 [Feat/22-ticketDetailPage] 이용권 세부 페이지 퍼블리싱
  src/App.tsx
  src/components/componentsLayout/Header.tsx
  src/components/index.ts
  src/components/ticketMain/CrewItem.tsx
  src/components/ticketMain/TicketCompItem.tsx
  src/components/ticketMain/TicketList.tsx
  src/components/ticketMain/index.ts
  src/components/ui/Button.tsx
  src/components/ui/index.ts
  src/constants/headerConstants.ts
  src/hooks/useFetchTicketDetail.ts
  src/hooks/useFetchTicketsList.ts
  src/pages/TicketDetailViewPage.tsx
  src/pages/index.ts
  src/styles/GlobalStyle.tsx
  src/styles/pagesStyles/ticketStyles/CrewItem.styled.ts
  src/styles/pagesStyles/ticketStyles/TicketDetailViewPage.styled.ts
  src/types/ticket.ts
  yarn.lock
Labels: Design, Feat

#33 [Feat/32-modalComponent] 모달 컴포넌트로 분리
  src/components/addressSearch/AddressPopup.tsx
  src/components/ui/PopUpModal.tsx
  src/components/ui/index.ts
  src/styles/componentsStyles/AddressPopUp.styled.ts
Labels: Refactor

#36 [Feat/34-CrewPopUp]- 크루 팝업 페이지 구현
  src/components/addressSearch/AddressPopup.tsx
  src/components/ticketMain/CategoryList.tsx
  src/components/ticketMain/CrewItem.tsx
  src/components/ticketMain/CrewPopUp.tsx
  src/components/ui/Button.tsx
  src/components/ui/Divide.tsx
  src/components/ui/PopUpModal.tsx
  src/pages/AddressSearchPage.tsx
  src/pages/CreateCrewPage.tsx
  src/pages/TicketDetailViewPage.tsx
  src/recoil/atom/addressModal.ts
  src/recoil/atom/crewInfo.ts
  src/recoil/atom/types.ts
  src/service/mutations/index.ts
  src/service/queries/index.ts
  src/styles/componentsStyles/AddressPopUp.styled.ts
  src/styles/pagesStyles/ticketStyles/CrewPopUp.styled.ts
  src/types/ticket.ts
Labels: Design, Feat

#40 [Feat/39-ticketReStyle] 이용권 리스트 스타일링 수정
  src/components/home/TicketItem.tsx
  src/components/ticketMain/CrewItem.tsx
  src/components/ticketMain/TicketCompItem.tsx
  src/pages/TicketDetailViewPage.tsx
  src/styles/pagesStyles/ticketStyles/CrewItem.styled.ts
  src/styles/pagesStyles/ticketStyles/TicketDetailViewPage.styled.ts
  src/styles/pagesStyles/ticketStyles/TicketItem.ts
Labels: Design

#42 [Feat/41-chart] 과거 이용권 추세 Chart 구현
  package.json
  src/components/home/TrendingChart.tsx
  src/components/home/index.ts
  src/constants/chartColorPalette.ts
  src/pages/HomePage.tsx
  src/recoil/atom/trendingPast.ts
  src/recoil/atom/types.ts
  src/recoil/selector/trendingPastChart.ts
  src/service/queries/index.ts
  yarn.lock
Labels: Design, Feat

#44 [Feat/35-crewManagePage] 크루 관리 페이지 구현
  package-lock.json
  src/App.tsx
  src/assets/icon/etc/filter_Default.png
  src/constants/headerConstants.ts
  src/constants/navLinks.ts
  src/pages/ManageCrewPage.tsx
  src/pages/NeighborPage.tsx
  src/pages/index.ts
  src/recoil/atom/myCrews.ts
  src/service/queries/index.ts
  src/styles/pagesStyles/manageCrewStyles/ManageCrewPage.styled.ts
  src/styles/pagesStyles/ticketStyles/CrewItem.styled.ts
  src/types/ticket.ts
  yarn.lock
Labels: Feat

#47 [Feat/43-loading] 로딩 컴포넌트 구현
  src/components/ui/Loading.tsx
  src/components/ui/PopUpModal.tsx
  src/hooks/useMyLocation.ts
  src/pages/AddressSearchPage.tsx
  src/recoil/atom/loading.ts
Labels: Design, Feat

#49 [ Fix/48 ] 현재 설정 주소 로컬스토리지 / Home 모달 세션으로 관리
  src/components/addressSearch/MyAddresses.tsx
  src/components/home/HomePopUp.tsx
  src/components/ui/Location.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/recoil/atom/userLocation.ts
Labels: Fix

#53 [Fix] pwa 에러 해결
  package.json
  src/global.d.ts
  src/main.tsx
  vite.config.ts
Labels: Fix

#55 [Feat/54-myPage] 마이페이지 퍼블리싱 & 회원정보 api 연동 & 로그아웃 구현
  dev-dist/sw.js
  dev-dist/workbox-54d0af47.js
  package-lock.json
  src/App.tsx
  src/constants/headerConstants.ts
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/recoil/atom/myCrews.ts
  src/recoil/atom/myPage.ts
  src/recoil/atom/types.ts
  src/service/mutations/index.ts
  src/service/queries/index.ts
  src/styles/pagesStyles/myPageStyles/myPage.Styled.ts
  yarn.lock
Labels: Design, Feat

#57 [Feat/56] 이용권 유튜브 영상 삽입 구현
  package.json
  src/components/home/TicketVideo.tsx
  src/components/home/index.ts
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  yarn.lock
Labels: Feat

#60 [Feat/59] 회원가입 유효성 검사 및 추가 CSS
  src/assets/icon/etc/signUpCircles.png
  src/components/addressSearch/SearchResults.tsx
  src/components/ui/BaseInput.tsx
  src/components/ui/LabelTitle.tsx
  src/hooks/index.ts
  src/hooks/useValid.ts
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/recoil/atom/types.ts
  src/styles/componentsStyles/componentsLayoutStyles/Input.styled.ts
  src/styles/pagesStyles/SignUpPage.styled.ts
Labels: Design, Enhancement, Feat

#62 [Feat/61] 이웃 세부 페이지 구현
  src/App.tsx
  src/components/componentsLayout/HeaderNav.tsx
  src/components/crew/ CrewItemDetail.tsx
  src/components/ui/AlertBanner.tsx
  src/components/ui/Title.tsx
  src/pages/CrewDetailPage.tsx
  src/pages/ManageCrewPage.tsx
  src/pages/TicketApplyPage.tsx
  src/pages/index.ts
  src/recoil/atom/crewDetail.ts
  src/recoil/atom/types.ts
  src/service/mutations/index.ts
  src/service/queries/index.ts
  src/styles/pagesStyles/crewDetailStyles/CrewDetailPage.styled.ts
  src/styles/pagesStyles/crewDetailStyles/CrewItemDetail.styled.ts
Labels: Design, Feat
