Repository TUK-SPORTIFY/sportify-frontend, pull requests merged in 2024-11, with the labels that each got.

#1 set: icon image 추가
  .github/workflows/calibreapp-image-actions.yml
  src/assets/icon/category/categoryA_Active.png
  src/assets/icon/category/categoryA_Default.png
  src/assets/icon/category/categoryB_Active.png
  src/assets/icon/category/categoryB_Default.png
  src/assets/icon/category/categoryC_Active.png
  src/assets/icon/category/categoryC_Default.png
  src/assets/icon/category/categoryD_Active.png
  src/assets/icon/category/categoryD_Default.png
  src/assets/icon/category/categoryE_Active.png
  src/assets/icon/category/categoryE_Default.png
  src/assets/icon/category/categoryF_Active.png
  src/assets/icon/category/categoryF_Default.png
  src/assets/icon/etc/arrow/downArrow_Brand.png
  src/assets/icon/etc/arrow/downArrow_Default.png
  src/assets/icon/etc/arrow/downArrow_White.png
  src/assets/icon/etc/arrow/leftArrow_Brand.png
  src/assets/icon/etc/arrow/leftArrow_Default.png
  src/assets/icon/etc/arrow/leftArrow_White.png
  src/assets/icon/etc/arrow/rightArrow_Brand.png
  src/assets/icon/etc/arrow/rightArrow_Default.png
  src/assets/icon/etc/arrow/rightArrow_White.png
  src/assets/icon/etc/arrow/upArrow_Brand.png
  src/assets/icon/etc/arrow/upArrow_Default.png
  src/assets/icon/etc/arrow/upArrow_White.png
  src/assets/icon/etc/notice_Brand.png
  src/assets/icon/etc/notice_Default.png
  src/assets/icon/etc/notice_White.png
  src/assets/icon/etc/period_Brand.png
  src/assets/icon/etc/period_Default.png
  src/assets/icon/etc/period_White.png
  src/assets/icon/etc/plus_Brand.png
  src/assets/icon/etc/plus_Default.png
  src/assets/icon/etc/plus_White.png
  src/assets/icon/etc/search_Brand.png
  src/assets/icon/etc/search_Default.png
  src/assets/icon/etc/search_White.png
  src/assets/icon/navigation/마이_Active.png
  src/assets/icon/navigation/마이_DeActive.png
  src/assets/icon/navigation/메인_Active.png
  src/assets/icon/navigation/메인_DeActive.png
  src/assets/icon/navigation/이용권_Active.png
  src/assets/icon/navigation/이용권_DeActive.png
  src/assets/icon/navigation/이웃_Active.png
  src/assets/icon/navigation/이웃_DeActive.png
Labels: Design

#3 [Feat/2-navHeader] nav바 & Header 제작
  src/App.tsx
  src/assets/icon/logo.svg
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/components/index.ts
  src/constants/index.ts
  src/constants/navLinks.ts
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/NeighborPage.tsx
  src/pages/index.ts
  src/styles/GlobalStyle.tsx
  src/styles/componentsSyles/Header.styled.ts
  src/styles/componentsSyles/Navbar.styled.ts
Labels: Feat

#14 [Feat/13-loginPage] 로그인페이지 퍼블리싱
  src/App.tsx
  src/assets/icon/etc/loginCircles.png
  src/components/home/MyNeighbors.tsx
  src/components/ui/BaseInput.tsx
  src/components/ui/Button.tsx
  src/pages/AddressSearchPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/index.ts
  src/styles/componentsStyles/componentsLayoutStyles/Header.styled.ts
  src/styles/componentsStyles/componentsLayoutStyles/Input.styled.ts
  src/styles/pagesStyles/LoginPage.styled.ts
  src/styles/pagesStyles/homeStyles/MyNeighbors.styled.ts
  src/styles/pagesStyles/homeStyles/tempCodeRunnerFile.ts
Labels: Design, Feat

#16 [Feat/15-createCrewPage] createCrewPage 퍼블리싱
  src/App.tsx
  src/assets/icon/etc/minus_Default.png
  src/components/createCrew/Capacity.tsx
  src/components/createCrew/ImageUpload.tsx
  src/components/createCrew/Rule.tsx
  src/components/createCrew/RuleItem.tsx
  src/components/createCrew/SelectItem.tsx
  src/components/createCrew/SelectList.tsx
  src/components/ui/Button.tsx
  src/components/ui/Title.tsx
  src/constants/headerConstants.ts
  src/constants/newCrew.ts
  src/hooks/useMyLocation.ts
  src/pages/CreateCrewPage.tsx
  src/pages/index.ts
  src/recoil/atom/newCrew.ts
  src/recoil/atom/types.ts
  src/styles/GlobalStyle.tsx
  src/styles/pagesStyles/createCrewStyles/Capacity.styled.ts
  src/styles/pagesStyles/createCrewStyles/CreateCrewPage.styled.ts
  src/styles/pagesStyles/createCrewStyles/Rule.styled.ts
Labels: Design, Feat

#19 [Feat/17-signUpPage] 회원가입 페이지 퍼블리싱
  src/components/createCrew/Capacity.tsx
  src/components/createCrew/ImageUpload.tsx
  src/components/createCrew/SelectItem.tsx
  src/components/createCrew/SelectList.tsx
  src/components/ui/BaseInput.tsx
  src/components/ui/Divide.tsx
  src/components/ui/LabelTitle.tsx
  src/components/ui/Title.tsx
  src/components/ui/index.ts
  src/constants/signUpInfo.ts
  src/pages/CreateCrewPage.tsx
  src/pages/SignUpPage.tsx
  src/recoil/atom/signUp.ts
  src/recoil/atom/types.ts
  src/styles/componentsStyles/componentsLayoutStyles/Input.styled.ts
  src/styles/pagesStyles/SignUpPage.styled.ts
  src/styles/pagesStyles/createCrewStyles/Capacity.styled.ts
  src/styles/pagesStyles/createCrewStyles/CreateCrewPage.styled.ts
Labels: Design, Feat

#10 [Feat/9-ticketCategory] 이용권 카테고리 분류 구현
  src/components/index.ts
  src/components/ticketMain/CategoryItem.tsx
  src/components/ticketMain/CategoryList.tsx
  src/components/ticketMain/DetailCategoryTitle.tsx
  src/components/ticketMain/TicketCompItem.tsx
  src/components/ticketMain/TicketList.tsx
  src/components/ticketMain/index.ts
  src/constants/categoryData.ts
  src/hooks/useFetchTickets.ts
  src/pages/TicketApplyPage.tsx
  src/recoil/atom/category.ts
  src/recoil/atom/types.ts
  src/styles/pagesStyles/ticketStyles/CategoryItem.styled.ts
  src/styles/pagesStyles/ticketStyles/TicketItem.ts
  src/styles/pagesStyles/ticketStyles/TicketList.ts
  src/types/ticket.ts
Labels: Design, Feat

#21 [Feat/20-loginAndSignUpApi] 로그인/회원가입 api 연동
  package.json
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/recoil/atom/types.ts
  src/service/customApi.ts
  src/service/mutations/customMutation.ts
  src/service/mutations/useLogin.ts
  src/service/mutations/useSignUp.ts
  src/styles/pagesStyles/LoginPage.styled.ts
  yarn.lock
Labels: Feat

#27 [Feat/26] 주소설정페이지 api 연동
  src/components/addressSearch/AddressPopup.tsx
  src/components/addressSearch/MyAddresses.tsx
  src/components/addressSearch/SearchResults.tsx
  src/components/ui/Location.tsx
  src/hooks/useMyLocation.ts
  src/hooks/useSerchAddress.ts
  src/pages/AddressSearchPage.tsx
  src/pages/HomePage.tsx
  src/recoil/atom/currentLocation.ts
  src/recoil/atom/location.ts
  src/recoil/atom/myAddresses.ts
  src/recoil/atom/types.ts
  src/recoil/atom/userLocation.ts
  src/service/mutations/index.ts
  src/service/queries/index.ts
Labels: Feat

#30 [Feat/29] 크루 생성 페이지 api연동
  src/components/createCrew/Capacity.tsx
  src/components/createCrew/ImageUpload.tsx
  src/components/createCrew/Rule.tsx
  src/components/createCrew/SelectList.tsx
  src/components/ui/Button.tsx
  src/components/ui/Title.tsx
  src/constants/newCrew.ts
  src/pages/CreateCrewPage.tsx
  src/recoil/atom/newCrew.ts
  src/service/mutations/index.ts
  src/styles/pagesStyles/createCrewStyles/CreateCrewPage.styled.ts
Labels: Feat, Fix

#31 [Feat/28] 홈화면 Api 연동 최종 완료 후 데이터 보여주기 구현
  src/components/home/ActiveTicketsList.tsx
  src/components/home/MyNeighbors.tsx
  src/components/home/TicketItem.tsx
  src/components/home/TrendingTickets.tsx
  src/pages/HomePage.tsx
  src/recoil/atom/activityTickets.ts
  src/recoil/atom/myCrews.ts
  src/recoil/atom/trendingTickets.ts
  src/recoil/atom/types.ts
  src/styles/pagesStyles/homeStyles/TicketItem.styled.ts
  src/types/ticket.ts
Labels: Design, Feat
